#+TITLE: Existing Software

This document contains details on software that will be useful in the project.

* anndata
* Scanpy [[[https://scanpy.readthedocs.io/][website]], [[https://github.com/theislab/scanpy][code]]]
Scanpy

* scvi-tools [[[https://scvi-tools.org/][website]], [[https://github.com/YosefLab/scvi-tools][code]]]
scvi-tools is a framework for dealing with single-cell annotated data `anndata` for use in machine learning models. It is built on top of Scanpy and provides extra functionality and processing steps for data, as well as prebuilt models for various single-cell tasks. Most of the tasks are centered around processing the data for further analysis, and there aren't any methods that are as involved as trajectory inference. It may be a possibility to write part of the trajectory inference code in this framework (at least at the dataprocessing stages), but more I'm anticipating that it will be helpful to understand how the framework works, as I lack some critical domain knowledge in single-cell and don't want to miss preprocessing steps etc. This framework will be useful for reference at least, and interfaces with PyTorch. Below are the APIs and submodules for the framework:

** User - functionality for performing single-cell data science [[[https://docs.scvi-tools.org/en/stable/api/user.html][reference]]]
The user framework allows for performing common single-cell data science tasks. It has the following submodules:
*** Model (scvi.model)
*** External models (scvi.external)
*** Data loading (scvi.data)

** Developer - APIs and classes for integrating user-defined models into scvi-tools [[[https://docs.scvi-tools.org/en/stable/api/developer.html][reference]]]
*** Data Loaders
*** Distributions
*** Model (Base)
*** Module
*** External module
*** Module (Base)
*** Neural networks
*** Train
*** Utilities

** Datasets - datasets useful for benchmarking models [[[https://docs.scvi-tools.org/en/stable/api/datasets.html][reference]]]


* PyTorchGraph
* Implicit-MLE
